name = "ProjectEuler"
uuid = "0aceee4e-dde8-4051-936d-3cb6edaa2490"
authors = ["Sukanka <su975853527@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"

[compat]
Combinatorics = "1"
BenchmarkTools = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
